default: &default
  adapter: oracle_enhanced
  database: xe 
  host: localhost/xe
  port: 1524

development:
  <<: *default
  username: dev_user
  password: devuser

test: &test
  <<: *default
  username: test_user
  password: testuser

cucumber:
  <<: *test